### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/CASCHost#15]
![image](https://user-images.githubusercontent.com/35412834/41737905-4cbe7e78-7599-11e8-902f-573cd707431a.png)

Going to localhost:5100/cdns doesn't download anything, /rebuild doesn't work, etc.

Deleting output and the sql table does not help

**Comment by Smerdokryl** [comment]
I did some googling and some people seem to have had no such problem with .NET Core 2.0, before they switched to 2.1., so I tried retargeting everything to 2.0. and recompiling, but it didn't help

**Comment by hoxton22** [comment]
i got the same issue :/

**Comment by justMaku** [comment]
I’ve found the underlying issue and should be able to fix it soon™️

**Comment by hoxton22** [comment]
Ok thanks you for the really fast asnwer, i thought it was a dll problem with .netcore versions !

**Comment by justMaku** [comment]
Hey there, could you please look if #16 fixed this for you? You'd have to run this branch: `bugfix/netcore-2.1.0-supported`

**Comment by hoxton22** [comment]
Nope, i got this

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLF8907TFDD0", Request id "0HLF8907TFDD0:00000001": An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at CASCHost.FileProvider.ProcessCommands(String path) in D:\Model Changing\CASC\Caschost\CASCHost\CASCHost\FileProvider.cs:line 47
   at CASCHost.FileProvider.GetFileInfo(String subpath) in D:\Model Changing\CASC\Caschost\CASCHost\CASCHost\FileProvider.cs:line 33
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 94.2276ms 500

**Comment by Smerdokryl** [comment]
I get this:

```
Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/rebuild
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 55.1722ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/rebuild
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2326ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/cdns
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.1017ms 404
```

**Comment by justMaku** [comment]
@hoxton22 are you sure you're running the `bugfix/netcore-2.1.0-supported` branch? From the exception it looks like you're still on `master`

@Smerdokryl It seems like it works, can you post the full log?

**Comment by hoxton22** [comment]
my apologizes, i did it really fast yesterday, i will try this tonight and tell u if it works

**Comment by justMaku** [comment]
@Smerdokryl this doesn't seem right? Can you post a screenshot of your CASCHost window?

**Comment by Smerdokryl** [comment]
@justMaku 
![image](https://user-images.githubusercontent.com/35412834/42698378-671586c0-86c6-11e8-9952-30146eac84fe.png)

**Comment by hoxton22** [comment]
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/rebuild
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 78.482ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/favicon.ico
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.4848ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5100/favicon.ico
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.1865ms 404

I got the 404 error too

**Comment by justMaku** [comment]
Oh, it’s a 404 🧐 guess I need to investigate more

**Comment by justMaku** [comment]
Sorry for this taking so long. It's finally fixed though and CASCHost should now work with dotnet core 2.1
