### ISSUE TITLE
Custom files not in root_entries

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/CASCHost#19]
Same as https://github.com/WowDevTools/CASCHost/issues/17, except running CASCHost any number of times doesn't help. root_entries only has _ROOT_ and _ENCODING_.

Appears both in Master and https://github.com/WowDevTools/CASCHost/tree/bugfix/netcore-2.1.0-support

**Comment by justMaku** [comment]
Duplicate of #17
