### ISSUE TITLE
[BfA] CAS system unable to initialize

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/CASCHost#23]
I have removed .build.info from the client, and the .exe has been edited accordingly. Also, this error did not occur when I used CASCHost, but had nothing in its Data folder (removing the files does not fix the issue, so I guess this was because I forgot to remove .build.info back then)

![image](https://user-images.githubusercontent.com/35412834/49030524-759b3480-f19f-11e8-805f-734a1171780d.png)

The .build.info mentioned (used for CASCHost):
```
Branch!STRING:0|Active!DEC:1|Build Key!HEX:16|CDN Key!HEX:16|Install Key!HEX:16|IM Size!DEC:4|CDN Path!STRING:0|CDN Hosts!STRING:0|CDN Servers!STRING:0|Tags!STRING:0|Armadillo!STRING:0|Last Activated!STRING:0|Version!STRING:0|Build Complete!DEC:1
eu|1|c19c4111371a31321f0161466c32094f|6befbbea8b82eab8e3ebe97e844910b2|11922a702b969d5487a7a15a7645dc1b||tpr/wow|level3.blizzard.com eu.cdn.blizzard.com blzddist1-a.akamaihd.net|http://blzddist1-a.akamaihd.net/?maxhosts=4 http://eu.cdn.blizzard.com/?maxhosts=4 http://level3.blizzard.com/?maxhosts=4 https://blzddist1-a.akamaihd.net/?fallback=1&maxhosts=4 https://eu.cdn.blizzard.com/?fallback=1&maxhosts=4 https://level3.ssl.blizzard.com/?fallback=1&maxhosts=4|Windows x86_64 EU? enUS speech?:Windows x86_64 EU? enUS text?:Windows x86_64 EU? ruRU speech?:Windows x86_64 EU? ruRU text?||2018-11-26T16:40:49Z|8.0.1.28153|1
```

**Comment by Izidor** [comment]
same issue here with the 8.0.1 28153

**Comment by HellSeagull** [comment]
Error in 8.0.1 28153
Basically, it looks like some keys are mismatch, mayeb it's linked to the fact that Blizzard is deleting old cdns and you removed the downloadurl linked to marlam.in ? I'm still trying to debug the source code on my side. Will keep you up if I find anything.

![wow_8rvvlhc75i](https://user-images.githubusercontent.com/16143020/51088180-db964800-175c-11e9-94d1-009ad08abe7f.png)

**Comment by HellSeagull** [comment]
Some more details on the error : 
As you can see, the range is null when trying to download custom files (if there's no custom files it works).
Meaning we don't get bytes and thus it's impossible to get the "partial content 206"
![dotnet_t6pjcrsbdt](https://user-images.githubusercontent.com/16143020/51088525-05516e00-1761-11e9-85cf-a89420c1e114.png)
![devenv_oje0wkfbeq](https://user-images.githubusercontent.com/16143020/51088526-05ea0480-1761-11e9-958e-5617c0e5f272.png)

**Comment by Smerdokryl** [comment]
Shelby from the WoW Modding Community discord has alleged that, once CASCHost is running, editing the versions output file by removing the last line and changing CDN hash to 71f05993e7b1603907cb43750af94502 results in it working with BfA and successfully delivering custom files

**Comment by Marlamin** [comment]
As the error mentions, the issue is in the fact that CASCHost adds an archive to the archives list in cdnconfig but does not add the size of the new index(es) to the archives-index-size list.

Size of the index needs to be added to archives-index-size around here: https://github.com/WowDevTools/CASCHost/blob/6ce4f3861a39e8a0a319c8b78747d34f98cff392/CASCEdit/Handlers/ArchiveIndex.cs#L185

**Comment by Smerdokryl** [comment]
@MaxtorCoder 's fix confirmed as working perfectly, for which he has my endless gratitude!

Atm, CASCHost is not compatible with Arctium's Launcher right away. For a fix, visit: https://model-changing.net/tutorials/article/120-beginners-guide-to-caschost/
