### ISSUE TITLE
mysqlconnector not found

### ISSUE THREAD

**Issue by ladiszlai** [WowDevTools/CASCHost#27]
Error:
  An assembly specified in the application dependencies manifest (CASCHost.deps.json) was not found:
    package: 'MySqlConnector', version: '0.42.0'
    path: 'lib/netcoreapp2.1/MySqlConnector.dll'

**I have .net core 2.1**

**Comment by MaxtorCoder** [comment]
Restore packages before building.

Open a CMD window and type 'dotnet build' that should restore that package.

**Comment by ladiszlai** [comment]
Thanks
