### ISSUE TITLE
No Global root found (WoW 9.0.1)

### ISSUE THREAD

**Issue by shearx** [WowDevTools/CASCHost#32]
As of the Shadowlands prepatch (9.0.1), the following error is received upon attempting to load CASCHost:

![image](https://user-images.githubusercontent.com/47221099/95942422-4a745b00-0da0-11eb-8f7d-9bd6bc50359f.png)

**Comment by bloerwald** [comment]
Have you tried with https://github.com/WowDevTools/CASCHost/pull/30?

**Comment by shearx** [comment]
> 
> 
> Have you tried with #30?

Yep but it doesn't fix the problem. I believe the issue is the content flags changed a bit, as there no longer are any chunks that satisfy this condition when it is looking for the global root:

**CASCEdit >> RootHandler.cs >> Line 51:**
`if (chunk.LocaleFlags == LocaleFlags.All_WoW && chunk.ContentFlags == ContentFlags.None)`

**Comment by rem999** [comment]
Надеюсь автор ещё жив? В repacke не работает.
I hope the author is still alive? It doesn't work in repacke.
Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки. 
Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.

https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs

**Comment by MaxtorCoder** [comment]
> Надеюсь автор ещё жив? В repacke не работает.
> I hope the author is still alive? It doesn't work in repacke.
> Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки. 
> Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.
> 
> https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs

How are Arctium greedy bastards? Please elaborate.

**Comment by Fabi** [comment]
> Надеюсь автор ещё жив? В repacke не работает.
> I hope the author is still alive? It doesn't work in repacke.
> Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки.
> Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.
> 
> https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs

works fine on pservers together with the launcher

**Comment by justMaku** [comment]
>I hope the author is still alive?

Not really.

**Comment by rem999** [comment]
> > Надеюсь автор ещё жив? В repacke не работает.
> > I hope the author is still alive? It doesn't work in repacke.
> > Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки.
> > Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.
> > https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs
> 
> works fine on pservers together with the launcher

Докажи?
Prove it?

**Comment by Fabi** [comment]
> > > Надеюсь автор ещё жив? В repacke не работает.
> > > I hope the author is still alive? It doesn't work in repacke.
> > > Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки.
> > > Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.
> > > https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs
> > 
> > 
> > works fine on pservers together with the launcher
> 
> Докажи?
> Prove it?

Just use it and stop insulting people. If you are not able to properly set it up that's your fault.

**Comment by rem999** [comment]
> > > > Надеюсь автор ещё жив? В repacke не работает.
> > > > I hope the author is still alive? It doesn't work in repacke.
> > > > Возможно испортили Arctium WoW Client Launcher. Им не заплатили они решили отомстить. Arctium жадные ублюдки.
> > > > Possibly messed up Arctium WoW Client Launcher. They were not paid, they decided to take revenge. Arctium are greedy bastards.
> > > > https://www.nexusmods.com/worldofwarcraft/mods/841/?tab=logs
> > > 
> > > 
> > > works fine on pservers together with the launcher
> > 
> > 
> > Докажи?
> > Prove it?
> 
> Just use it and stop insulting people. If you are not able to properly set it up that's your fault.

Девонька помолчи. Если ни чего не знаешь.
Little girl, shut up. If you don't know anything.

**Comment by justMaku** [comment]
And this is why the author is dead.
