### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by Smerdokryl** [WowDevTools/CASCHost#4]
I made sure that the login and password are correct (and truice, for example, connects perfectly well with those), but still get the error. What are the other possible causes?

**Comment by bloerwald** [comment]
In line 144 of CASCHost/Cache.cs, print the `catch`ed exception with a debugger or to the logger to see the actual error.

**Comment by Smerdokryl** [comment]
I tried debugging in Visual Studio and I get the following things, but I don't know whether they are relevant.
![image](https://user-images.githubusercontent.com/35412834/40581865-31b69f22-615b-11e8-8607-e802441064c9.png)
![image](https://user-images.githubusercontent.com/35412834/40581866-356afcee-615b-11e8-9fed-67f7d62d959e.png)
![image](https://user-images.githubusercontent.com/35412834/40581868-37f6dd66-615b-11e8-94d3-277b8bce543d.png)

If that's not what is needed, I'm afraid I don't understand what exactly you asked me to do. Please, accept my apologies for lack of savviness in C#, debugging, and life in general.

**Comment by Smerdokryl** [comment]
I got the latest version, and the log showed simply 'unknown database *name*'. Creating the empty database manually has solved the problem. 

Thanks, @barncastle !
